
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '5E9B8AAAD08E23324150AF153E216576'
    
_lr_action_items = {'PRINT':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[1,-18,-19,-22,-20,-24,-23,-17,-16,1,-4,1,-10,-12,-11,-9,-5,]),'QUOTE':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[2,-18,-19,-22,-20,-24,-23,-17,-16,2,-4,2,-10,-12,-11,-9,-5,]),'$end':([0,3,4,5,6,7,8,9,10,11,12,13,14,16,24,],[-21,-18,-19,-22,-2,-20,-3,-24,-23,0,-1,-17,-16,-4,-5,]),'NUM':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[4,-18,-19,-22,-20,-24,-23,-17,-16,4,-4,4,-10,-12,-11,-9,-5,]),'LPAREN':([2,],[15,]),'TRUE':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[5,-18,-19,-22,-20,-24,-23,-17,-16,5,-4,5,-10,-12,-11,-9,-5,]),'TEXT':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[7,-18,-19,-22,-20,-24,-23,-17,-16,7,-4,7,-10,-12,-11,-9,-5,]),'RPAREN':([3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,22,23,24,],[-18,-19,-22,-20,-24,-23,-17,-16,-8,-4,-8,-10,-7,-11,-9,24,-6,-5,]),'CONTENTS':([1,],[14,]),'NIL':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[9,-18,-19,-22,-20,-24,-23,-17,-16,9,-4,9,-10,-12,-11,-9,-5,]),'FALSE':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[10,-18,-19,-22,-20,-24,-23,-17,-16,10,-4,10,-10,-12,-11,-9,-5,]),'SYMB':([0,3,4,5,7,9,10,13,14,15,16,17,18,19,20,21,24,],[13,-18,-19,-22,-20,-24,-23,-17,-16,13,-4,13,-10,-12,-11,-9,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'item':([15,17,],[17,17,]),'bool':([0,15,17,],[3,3,3,]),'quoted_list':([0,15,17,],[6,18,18,]),'list':([2,],[16,]),'empty':([15,17,],[19,19,]),'call':([0,15,17,],[8,20,20,]),'exp':([0,],[11,]),'atom':([0,15,17,],[12,21,21,]),'items':([15,17,],[22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> atom','exp',1,'p_exp_atom','yacc.py',134),
  ('exp -> quoted_list','exp',1,'p_exp_qlist','yacc.py',138),
  ('exp -> call','exp',1,'p_exp_call','yacc.py',142),
  ('quoted_list -> QUOTE list','quoted_list',2,'p_quoted_list','yacc.py',146),
  ('list -> LPAREN items RPAREN','list',3,'p_list','yacc.py',152),
  ('items -> item items','items',2,'p_items','yacc.py',156),
  ('items -> empty','items',1,'p_items_empty','yacc.py',160),
  ('empty -> <empty>','empty',0,'p_empty','yacc.py',164),
  ('item -> atom','item',1,'p_item_atom','yacc.py',168),
  ('item -> quoted_list','item',1,'p_item_list','yacc.py',176),
  ('item -> call','item',1,'p_item_call','yacc.py',180),
  ('item -> empty','item',1,'p_item_empty','yacc.py',184),
  ('contents -> CONTENTS','contents',1,'p_contents','yacc.py',188),
  ('print -> PRINT','print',1,'p_print','yacc.py',193),
  ('printline -> PRINT CONTENTS','printline',2,'p_printline','yacc.py',198),
  ('call -> PRINT CONTENTS','call',2,'p_call','yacc.py',203),
  ('atom -> SYMB','atom',1,'p_atom_symbol','yacc.py',215),
  ('atom -> bool','atom',1,'p_atom_bool','yacc.py',219),
  ('atom -> NUM','atom',1,'p_atom_num','yacc.py',223),
  ('atom -> TEXT','atom',1,'p_atom_word','yacc.py',227),
  ('atom -> <empty>','atom',0,'p_atom_empty','yacc.py',231),
  ('bool -> TRUE','bool',1,'p_true','yacc.py',235),
  ('bool -> FALSE','bool',1,'p_false','yacc.py',239),
  ('atom -> NIL','atom',1,'p_nil','yacc.py',243),
]
